name: Build

on:
  workflow_dispatch:
    inputs:
      node:
        description: 'Node major version'
        required: true
        default: '12'
      arch:
        description: 'Arch'
        required: true
        default: 'arm64'
      os:
        description: 'OS'
        required: true
        default: 'linux'
jobs:
  apk:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v1

      - name: "Build ${{ github.event.inputs.arch }} node${{ github.event.inputs.node }} ${{ github.event.inputs.os }}"
        timeout-minutes: 360
        id: build
        run: |
          sudo apt-get install -y rename
          chmod +x build.sh
          ./build.sh ${{ github.event.inputs.arch }} node${{ github.event.inputs.node }} ${{ github.event.inputs.os }}
          FETCHED=$(ls | grep fetched)
          echo "::set-output name=FETCHED::$FETCHED"
      - name: Upload {{ steps.build.outputs.FETCHED }} to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ steps.build.outputs.FETCHED }}
          asset_name: ${{ steps.build.outputs.FETCHED }}
          tag: node${{ github.event.inputs.node }}
          overwrite: true
